version: '3'
services:
  web:
    container_name: angular-app
    build:
      context: ./.docker/web
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
